#!/bin/bash
# child

. functions 
temp="tmp.$$"

while true
    do
        dialog --menu "Choose one of the options" 15 30 10 \
	1 "Operating system type" \
	2 "CPU" \
	3 "Memory information" \
	4 "Hard disk information" \
	5 "Go back" \
			2>$temp
	result=$?
	clear

        if [ $result = 1 ] || [ $result = 255 ]; then
      	     closeChild
    	fi 

    	answer=`cat $temp`

    	case $answer in
	    "1") message "$(uname -a)" 6 80 ;;
	    "2") message "$(lscpu)" 40 160 ;;
	    "3") message "$(free -h) " 8 60  ;;
	    "4") message "$(df -h)"  28 80;;
	    "5") closeChild ;;
     	esac
    done
