#!/bin/bash
# tell the os to invoke speciefied shell 
# temp="tmp.$$"

# function message displays dialog infobox with parameters given when invoking the function 
function message {
    dialog --msgbox "$1" $2 $3
   }

# function end, terminates execution of the progeam if user selected exit or pressed Esc button
function end {
    if [ "$1" = "1" ] || [ "$1" = "255" ]; then  # check if variable matches exit code
    	message "$2" 5 35 # display infobox using parameter passed to the function and use 5 as height and 35 as width
    	clear # clear the screen
    	rm -f $temp # remove temporary file
    exit # terminate the program
    fi
}

# deletes the file
function delete_file {
     dialog --yesno "Are you sure you want to delete? \n $FILE" 7 50 #use yes no dialog box to confirm deletion
         if  [ $? = 0 ]; then # use exit code to confirm deletion             
            if [ ! -e "$1" ]; then  # if file doesn't exist use function message to notify user 
                 message "File does not exist." 10 30
            else
                  rm -f $1 # otherwise delete file and display confirmation 
                  message "$1 has been deleted succsssfully" 0 0 
            fi
         else # if exit code !(0) display the message operation terminated
              message "Operation has been aborted by the user" 5 43
         fi
} 


function isFile {
     dialog --inputbox "Enter path: " 5 40 "$(pwd)/" 2> $temp # display inputbox and save the value to temp file
     path=`cat $temp` # assign value stroed in temp file to variable path
     # store path selected in dialogbox in varialbe FILE
     FILE=$(dialog --title "Delete a file" --stdout --title \
     "Please choose a file to delete" --fselect "$path" 20 100)
     if [ $? = 0 ]; then # if exit code = 0 
         if [ -d "$FILE" ]; then # checks if path is directory
              message "This path is not a file" 5 30  # if it is directory display error message
         else # if it isn't invoke function delete file 
              delete_file $FILE
         fi
     else # display if cancelled pressed in fselect
         message "Operation has been aborted by the user" 5 53
     fi
}

