#!/bin/bash
# tell the os to invoke speciefied shell 

# CST1500 Coursework 2 

# M00724948 - Sebastian Sokalski 

# M00737687 - Sebastiaan Gastol

# functions file

# function message displays dialog infobox with parameters given when invoking the function 
function message {
    dialog --msgbox "$1" $2 $3
   }

# function end, terminates execution of the progeam if user selected exit or pressed Esc button
	function end {
    if [ "$1" = "1" ] || [ "$1" = "255" ]; then  # check if variable matches exit code
    	message "$2" $3 $4 # display infobox using parameter passed to the function and use 5 as height and 35 as width
    	clear # clear the screen
    	rm -f $temp # remove temporary file
    exit # terminate the program
    fi
}

# deletes the file
function delete_file {
    if [ ! -e "$1" ]; then  # if file doesn't exist use function message to notify user 
         message "File does not exist." 5 24
    else
        dialog --yesno "Are you sure you want to delete? \n $FILE" 6 50 #use yes no dialog box to confirm deletion
        if  [ $? = 0 ]; then # use exit code to confirm deletion    
            rm -f $1 # otherwise delete file and display confirmation 
            message "$1 has been deleted succsssfully." 0 0          
         else # if exit code !(0) display the message operation terminated
              message "Operation has been aborted by the user." 5 44
         fi 
    fi
} 

# checks if selected path is a file
function isFile {
     dialog --inputbox "Enter path or press enter to stay in current directory: " \
 	5 60 "$(pwd)/" 2> $temp # display inputbox and save the value to temp file
     path=`cat $temp` # assign value stroed in temp file to variable path
     # store path selected in dialogbox in varialbe FILE
     FILE=$(dialog --title "Delete a file" --stdout --title \
     "Please choose a file to delete" --fselect "$path" 20 100)
     if [ $? = 0 ]; then # if exit code = 0 
         if [ -d "$FILE" ]; then # check if path is directory
              message "This path is not a file." 5 30  # if it is directory display error message
         else # if it isn't invoke function delete file 
              delete_file $FILE
         fi
     else # display if cancelled pressed in fselect
         message "Operation has been aborted by the user." 5 44
     fi
}

